### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by z-jo-murata** [atom/ide-php#109]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.7.8

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/z.jo.murata/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -1:36.2.0 core:move-up (input.hidden-input)
     -1:32.1.0 core:select-right (input.hidden-input)
     -1:30.2.0 core:backspace (input.hidden-input)
     -1:26.1.0 core:copy (input.hidden-input)
     -1:24.8.0 core:paste (input.hidden-input)
     -1:24.3.0 core:save (input.hidden-input)
  8x -0:42 core:undo (input.hidden-input)
  2x -0:37.8.0 core:save (input.hidden-input)
  2x -0:27.7.0 core:move-down (input.hidden-input)
  5x -0:26.4.0 core:move-up (input.hidden-input)
  3x -0:24.6.0 core:move-down (input.hidden-input)
     -0:12.9.0 core:backspace (input.hidden-input)
     -0:12.3.0 core:move-right (input.hidden-input)
  2x -0:12.1.0 core:move-up (input.hidden-input)
     -0:11.3.0 core:select-down (input.hidden-input)
     -0:11 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
atom-ide-ui 0.9.2 
auto-encoding 0.7.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
file-icons 2.1.17 
git-plus 7.10.0 
highlight-selected 0.13.1 
ide-php 0.7.8 
ide-ruby 0.1.9 
ide-typescript 0.7.5 
intentions 1.1.5 
japanese-menu 1.14.0 
japanese-word-selection 0.5.1 
linter 2.2.0 
linter-erb 1.1.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-ruby 1.2.6 
linter-ui-default 1.7.0 
merge-conflicts 1.4.5 
minimap 4.29.8 
php-debug 0.2.6 
platformio-ide-terminal 2.8.0 
script 3.17.3 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by rsese** [comment]
Thanks for the report! Do you remember what you were doing when the error happened?  And can you confirm if the error is reproducible?

**Comment by damieng** [comment]
No response.
