### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by batcom** [atom/ide-php#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Deepin 15.4
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.6.1

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /home/coolnet/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:191

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:191:27)
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -1:22.9.0 core:backspace (input.hidden-input)
     -1:22.4.0 intentions:highlight (input.hidden-input)
     -1:22.2.0 core:save (input.hidden-input)
  2x -1:18.6.0 core:move-up (input.hidden-input)
     -1:11.1.0 intentions:highlight (input.hidden-input)
     -1:11 core:save (input.hidden-input)
     -0:57.7.0 core:move-down (input.hidden-input)
 35x -0:57.5.0 core:move-right (input.hidden-input)
     -0:54.3.0 core:backspace (input.hidden-input)
 13x -0:53.2.0 core:move-right (input.hidden-input)
     -0:52 core:backspace (input.hidden-input)
  2x -0:50.8.0 core:move-down (input.hidden-input)
     -0:49.4.0 core:move-left (input.hidden-input)
     -0:48.1.0 intentions:highlight (input.hidden-input)
     -0:47.9.0 core:save (input.hidden-input)
 31x -0:35.5.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-ide-ui 0.3.1 
autocomplete-python 1.10.2 
busy-signal 1.4.3 
goto-definition 1.3.4 
hyperclick 0.0.0 
ide-go 0.2.0 
ide-java 0.6.0 
ide-php 0.6.1 
ide-python 0.1.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-vue 0.23.1 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.2.4 
php-cs-fixer 4.1.0 
php-integrator-navigation 1.2.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, what are the steps to reproduce?

**Comment by damieng** [comment]
Improved error handling should give us better information when this happens again.  Will close this issue so we can capture more information from the next time it happens.
