### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by UziTech** [atom/ide-php#73]
[Enter steps to reproduce:]

This is very weird. I don't know which package to write the issue to.

I had ide-php installed and I was working on a typescript project so I installed ide-typescript. Then I started getting an error `Uncaught Error: Connection is closed.` from ide-php. I decided to disable ide-php for the time being since I didn't need it, but the error kept showing up.

I uninstalled ide-php, restarted Atom, and restarted my computer, but I still get the error from `~\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js` **which doesn't exist on my computer**

If I disable ide-typescript the error goes away.

same issue as https://github.com/atom/ide-typescript/issues/17#issuecomment-343573699

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: 'ide-php' package vundefined

### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\tjbrix\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:613

Error: Connection is closed.
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:131:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:181:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/text-editor.js:588:26)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:833:26)
    at DisplayLayer.didChange (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:828:57)
    at decorationLayerDisposable.textDecorationLayer.onDidInvalidateRange (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:162:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tokenized-buffer.js:324:26)
    at _.defer (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tokenized-buffer.js:291:63)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -0:38.6.0 window:toggle-dev-tools (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode undefined 
atom-beautify 0.30.6 
atom-ide-ui 0.5.4 
atom-jasmine 0.8.1 
atom-minify 0.8.0 
atom-typescript 11.0.10 
atomic-chrome 0.3.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.0 
change-case 0.6.5 
chrome-color-picker 0.8.0 
code-peek 1.4.21 
context-git 0.17.6 
context-menu-remove 0.1.0 
cson 2.0.1 
cursor-history 0.12.0 
dbclick-tree-view 1.6.3 
docblockr 0.13.2 
double-tag 1.1.0 
editor-stats 0.17.0 
editorconfig 2.2.2 
emmet 2.4.3 
external-open 0.6.3 
file-icons 2.1.13 
file-types 0.5.5 
file-watcher 1.2.6 
flex-tool-bar 0.12.0 
git-time-machine 1.5.9 
grammar-token-limit 0.1.1 
highlight-selected 0.13.1 
hyperclick 0.0.0 
hyperclick-php 0.2.1 
hyperlink-hyperclick 1.3.4 
ide-typescript 0.7.0 
intentions 1.1.5 
js-hyperclick 1.12.1 
keybinding-cheatsheet 0.1.1 
language-babel 2.78.0 
language-batch 0.4.0 
language-htaccess 0.1.1 
language-ini 1.19.0 
language-vbscript 0.9.0 
line-diff-details 1.9.0 
line-ending-converter 1.3.2 
linter-coffeelint 1.3.1 
linter-eslint 8.4.0 
linter-htmlhint 1.4.0 
linter-js-yaml 1.2.8 
linter-markdown 5.2.0 
linter-phpcs 1.6.8 
linter-sass-lint 1.8.3 
linter-twig 0.4.2 
linter-write-good 0.9.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
my-settings-view 0.252.2 
node-debugger 1.10.1 
notifications-plus 0.69.11 
notifications-plus-confetti 0.1.4 
npm-install 4.0.4 
open 0.1.1 
open_in_cmd 0.6.1 
open-in-developer-mode 0.3.0 
php-debug 0.2.5 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-refactoring 1.4.1 
php-twig 4.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
process-palette 0.15.2 
project-manager 3.3.5 
react 0.17.0 
Remote-FTP 1.3.1 
rest-client 1.3.1 
sass-autocompile 0.13.3 
script undefined 
scroll-editor-on-middle-click 0.4.0 
scroll-sync 0.2.3 
sort-lines 0.18.0 
split-diff 1.5.1 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.3 
text-manipulation 0.6.0 
todo-show 2.1.0 
tool-bar 1.1.0 
trailing-semicolon 1.1.0 
trailing-spaces 0.4.0 
transpile 0.1.4 
transpile-decaf 0.1.3 
tree-view-git-status 1.4.0 
uzitech-toggle-quotes 0.0.0 
vic 0.0.0 
wakatime 7.0.4 
web-accessibility-checker 0.1.4 
Zen 0.18.0 
```

**Comment by developer-lindner** [comment]
Even if the package is disabled the error occurs... pretty annoying!

**Comment by UziTech** [comment]
It seems to be the `ide-typescript` package that is actually throwing the error. I can't figure out why Atom thinks it is coming from `ide-php`

**Comment by roelofr** [comment]
Just throwing in my two cents, I don't have `ide-typescript` installed. 

The PHP server on occassion seems to crash with a memory error, causing the error to exist from that point.

```
PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 41947136 bytes) in /home/roelof/.atom/packages/ide-php/vendor/felixfbecker/language-server/src/Index/Index.php on line 222
```

## System information:


**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package 0.6.10


### Stack Trace

Uncaught Error: Connection is closed.

```
At /home/roelof/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:143:10)
    at ServerManager.projectFilesChanged (/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:233:33)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /usr/share/atom/resources/app/src/project.js:341:40
    at PathWatcher.onNativeEvents (/usr/share/atom/resources/app/src/path-watcher.js:671:15)
    at /usr/share/atom/resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/usr/share/atom/resources/app/src/path-watcher.js:448:26)
    at handler (/usr/share/atom/resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -3:16.9.0 docblockr:parse-tab (input.hidden-input)
     -3:16.9.0 snippets:next-tab-stop (input.hidden-input)
     -3:16.9.0 snippets:expand (input.hidden-input)
     -3:16.8.0 editor:indent (input.hidden-input)
     -3:16.7.0 intentions:highlight (input.hidden-input)
     -3:16.6.0 core:paste (input.hidden-input)
     -3:15.5.0 core:backspace (input.hidden-input)
     -3:13.1.0 intentions:highlight (input.hidden-input)
     -3:12.9.0 core:copy (input.hidden-input)
     -3:09.7.0 core:backspace (input.hidden-input)
     -3:06.5.0 intentions:highlight (input.hidden-input)
     -3:06.4.0 core:select-all (input.hidden-input)
     -3:06.2.0 core:copy (input.hidden-input)
     -1:55.1.0 intentions:highlight (input.hidden-input)
     -1:55.1.0 core:select-all (input.hidden-input)
     -1:54.9.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.3 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-ide-ui 0.5.4 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atom-no-tab-close-button 1.0.0 
atom-npm 0.3.1 
audio 1.5.7 
autocomplete-asciidoc 0.1.2 
autocomplete-java 1.2.7 
autocomplete-semantic-web 0.0.9 
battery-status 0.11.7 
blame 0.12.0 
build 0.69.0 
build-dockerfile 1.0.1 
build-grunt 0.4.0 
build-gulp 0.11.0 
build-make 0.13.0 
build-npm-apm 0.12.0 
busy 0.7.0 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
city-lights-syntax 1.1.2 
city-lights-ui 1.1.6 
color-picker 2.2.5 
css-snippets 1.1.0 
docblockr 0.13.2 
docker 0.8.0 
editorconfig 2.2.2 
file-icons 2.1.13 
git-log 0.4.1 
github-issues 0.9.0 
ide-php 0.6.10 
intentions 1.1.5 
language-asciidoc 1.11.0 
language-babel 2.79.0 
language-batchfile 0.7.0 
language-blade 0.36.0 
language-csv 1.1.2 
language-docker 1.1.8 
language-dotenv 1.1.1 
language-gettext 0.6.1 
language-gitignore 0.3.0 
language-gmod-lua 0.4.0 
language-htaccess 0.1.1 
language-ini 1.19.0 
language-keyvalue 0.1.0 
language-latex 1.1.1 
language-nginx 0.8.0 
language-patch 1.2.0 
language-pgsql 0.2.3 
language-plantuml 0.2.0 
language-sql-mysql 0.3.1 
language-svg 0.9.2 
language-twig 1.6.3 
language-zone 0.1.0 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-glua 1.2.1 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-lua 1.0.4 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-git-diff 4.3.1 
minimap-linter 2.1.3 
mocha-ui 0.1.8 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
pdf-view 0.61.0 
plantuml-preview 0.12.9 
project-view 0.6.2 
sass-autocompile 0.13.3 
save-workspace 0.4.0 
single-click-open 0.2.2 
ssh-config 0.12.0 
svg-preview 0.11.0 
sync-settings 0.8.3 
tablr 1.8.3 
theme-switch 0.5.0 
todo-show 2.1.0 
tree-view-git-status 1.4.0 
uuidgen 1.2.1 
word-jumper-deluxe 1.3.0 
wordcount 2.10.4 
```

**Comment by madebr** [comment]
I can reproduce this error with the following php snippet:
```php
<?php
function foo($bar=true) {
    function inner($bar=$bar) {
    }
}
?>
```

**Comment by kikoseijo** [comment]
This issue its something weird more related to atom, it goes crazy somethings because does not open the projects right.
After you restart atom it goes away.

**Comment by egesu** [comment]
Wow it's pretty annoying. I've been using this extension for several months and it started to appear one hour ago and I'm going crazy. The alert is shown on each key I press. Restarting atom fixes the issue for one minute :-)

**Comment by ivodvb** [comment]
Same issue here

1. Open Atom;
2. Just open any php file or even JS file, try to save it and the errror comes up;

- Already disabled ide-php, but that doesn't help;
- Removing ide-php seemed to help;

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [ide-php](https://github.com/atom/ide-php) package undefined


### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/ivovanbeek/.atom/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-php/node_modules/atom-languageclient/build/lib/languageclient.js:167:10)
    at ServerManager.projectFilesChanged (/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:248:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/Applications/Atom.app/Contents/Resources/app/src/project.js:357:28)
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -1:08.0 core:move-left (input.hidden-input)
     -1:06.3.0 core:save (input.hidden-input)
     -0:49.8.0 core:move-down (input.hidden-input)
     -0:49.7.0 core:move-left (input.hidden-input)
     -0:49.6.0 core:move-down (input.hidden-input)
     -0:49.6.0 core:move-left (input.hidden-input)
     -0:49.5.0 core:move-down (input.hidden-input)
  2x -0:49.3.0 core:move-left (input.hidden-input)
     -0:49.1.0 core:move-up (input.hidden-input)
  5x -0:48.8.0 core:move-left (input.hidden-input)
  3x -0:47.7.0 core:backspace (input.hidden-input)
  3x -0:46.3.0 core:move-left (input.hidden-input)
     -0:45.6.0 core:move-down (input.hidden-input)
  6x -0:45.4.0 core:move-left (input.hidden-input)
     -0:43.5.0 core:backspace (input.hidden-input)
     -0:42.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.3 
artisan 0.3.2 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-clock 0.1.16 
atom-ide-ui 0.8.1 
atom-spotify2 2.1.2 
atom-symfony2 0.3.0 
atom-ternjs 0.18.3 
atom-yarn 0.6.0 
busy-signal 1.4.3 
composer 0.5.0 
docblockr 0.13.6 
file-icons 2.1.16 
git-plus 7.10.0 
ide-php 0.7.5 
ide-typescript 0.7.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-blade 0.38.0 
laravel 0.7.1 
npm-install 4.0.4 
php-cs-fixer 4.1.1 
php-integrator-autocomplete-plus 1.6.2 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
pure-syntax 0.3.0 
react 0.17.0 
react-snippets 1.0.1 
symfony-snippets 0.3.0 
teletype 0.8.0 
toggl 0.6.0 
vagrant 0.1.0 
```
