### ISSUE TITLE
Language server cause UnexpectedValueException when initializing project

### ISSUE THREAD

**Issue by solaz3** [atom/ide-php#89]
Uncaught (in promise) Error: UnexpectedValueException: RecursiveDirectoryIterator::__construct(D:/www/pan.ai\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\es5-ext\node_modules\es6-iterator\node_modules\es6-symbol\node_modules\es5-ext\node_modules\es6-iterator\node_modules\es6-symbol\node_modules\es5-ext\node_modules\es6-iterator\node_modules\es6-symbol\node_modules\es5-ext,D:/www/pan.ai\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node in C:\Users\jh.ou\.atom\packages\ide-php\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\jh.ou\.atom\packages\ide-php\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('D:/www/pan.ai\\n...', 4128)
#1 C:\Users\jh.ou\.atom\packages\ide-php\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('D:/www/pan.ai\\n...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\jh.ou\.atom\packages\ide-php\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\jh.ou\.atom\packages\ide-php\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->next()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 C:\Users\jh.ou\.atom\packages\ide-php\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\jh.ou\.atom\packages\ide-php\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\jh.ou\.atom\packages\ide-php\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\jh.ou\.atom\packages\ide-php\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\jh.ou\.atom\packages\ide-php\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\jh.ou\.atom\packages\ide-php\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\jh.ou\.atom\packages\ide-php\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#14 {main}
    at new ResponseError (C:\Users\jh.ou\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
    at handleResponse (C:\Users\jh.ou\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:430:48)
    at processMessageQueue (C:\Users\jh.ou\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:258:17)
    at Immediate.<anonymous> (C:\Users\jh.ou\.atom\packages\ide-php\node_modules\vscode-jsonrpc\lib\main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

it just happened in this project, others worked fine which contains node_modules too.
I have no idea why it scanning node_modules, is it possible to add options to exclude some folders?

**Comment by solaz3** [comment]
Problem resovled! 
it seems that I am using a "hacked" version of npm to install packages and it created tons of symbol links for these packages then cause the language server scanning the wrong paths. 😂
